from csp_lib.modbus import ByteOrder, FunctionCode, Int32, UInt32
from csp_lib.equipment.core import ReadPoint, pipeline, ScaleTransform, RoundTransform
from csp_lib.equipment.core.point import PointMetadata

# PM335 Total Power Meter - point definitions (no alarm definitions)
# Source: Referance.py PM335 class (lines 737-790)
# Byte order: LITTLE_ENDIAN (original endian=Endian.LITTLE)

PM335_pm_read_points = [
    ReadPoint(
        name="p",
        address=13696,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="總實功功率"),
    ),
    ReadPoint(
        name="v_a",
        address=13952,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="A相電壓"),
    ),
    ReadPoint(
        name="v_b",
        address=13954,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="B相電壓"),
    ),
    ReadPoint(
        name="v_c",
        address=13956,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="C相電壓"),
    ),
    ReadPoint(
        name="i_a",
        address=13958,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.01), RoundTransform(2)),
        metadata=PointMetadata(unit="A", description="A相電流"),
    ),
    ReadPoint(
        name="i_b",
        address=13960,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.01), RoundTransform(2)),
        metadata=PointMetadata(unit="A", description="B相電流"),
    ),
    ReadPoint(
        name="i_c",
        address=13962,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.01), RoundTransform(2)),
        metadata=PointMetadata(unit="A", description="C相電流"),
    ),
    ReadPoint(
        name="p_a",
        address=13964,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="A相實功功率"),
    ),
    ReadPoint(
        name="p_b",
        address=13966,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="B相實功功率"),
    ),
    ReadPoint(
        name="p_c",
        address=13968,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="C相實功功率"),
    ),
    ReadPoint(
        name="q_a",
        address=13970,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAR", description="A相虛功功率"),
    ),
    ReadPoint(
        name="q_b",
        address=13972,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAR", description="B相虛功功率"),
    ),
    ReadPoint(
        name="q_c",
        address=13974,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAR", description="C相虛功功率"),
    ),
    ReadPoint(
        name="s_a",
        address=13976,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVA", description="A相視在功率"),
    ),
    ReadPoint(
        name="s_b",
        address=13978,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVA", description="B相視在功率"),
    ),
    ReadPoint(
        name="s_c",
        address=13980,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVA", description="C相視在功率"),
    ),
    ReadPoint(
        name="pf_a",
        address=13982,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(description="A相功率因數"),
    ),
    ReadPoint(
        name="pf_b",
        address=13984,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(description="B相功率因數"),
    ),
    ReadPoint(
        name="pf_c",
        address=13986,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(description="C相功率因數"),
    ),
    ReadPoint(
        name="vl_ab",
        address=14012,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="A-B線電壓"),
    ),
    ReadPoint(
        name="vl_bc",
        address=14014,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="B-C線電壓"),
    ),
    ReadPoint(
        name="vl_ca",
        address=14016,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="C-A線電壓"),
    ),
    ReadPoint(
        name="q",
        address=14338,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAR", description="總虛功功率"),
    ),
    ReadPoint(
        name="s",
        address=14340,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVA", description="總視在功率"),
    ),
    ReadPoint(
        name="pf",
        address=14342,
        data_type=Int32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(description="功率因數"),
    ),
    ReadPoint(
        name="v",
        address=14356,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="平均相電壓"),
    ),
    ReadPoint(
        name="vl",
        address=14358,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="平均線電壓"),
    ),
    ReadPoint(
        name="i",
        address=14360,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.01), RoundTransform(2)),
        metadata=PointMetadata(unit="A", description="平均電流"),
    ),
    ReadPoint(
        name="f",
        address=14468,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.01), RoundTransform(2)),
        metadata=PointMetadata(unit="Hz", description="頻率"),
    ),
    ReadPoint(
        name="imp_kwh",
        address=14720,
        data_type=UInt32(),
        function_code=FunctionCode.READ_INPUT_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kWh", description="輸入累積電量"),
    ),
    ReadPoint(
        name="exp_kwh",
        address=14722,
        data_type=UInt32(),
        function_code=FunctionCode.READ_INPUT_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kWh", description="輸出累積電量"),
    ),
    ReadPoint(
        name="tot_kwh",
        address=14726,
        data_type=UInt32(),
        function_code=FunctionCode.READ_INPUT_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kWh", description="總電量"),
    ),
    ReadPoint(
        name="imp_kvarh",
        address=14728,
        data_type=UInt32(),
        function_code=FunctionCode.READ_INPUT_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVARh", description="輸入累積無效電量"),
    ),
    ReadPoint(
        name="exp_kvarh",
        address=14730,
        data_type=UInt32(),
        function_code=FunctionCode.READ_INPUT_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVARh", description="輸出累積無效電量"),
    ),
    ReadPoint(
        name="tot_kvarh",
        address=14734,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVARh", description="總無效電量"),
    ),
    ReadPoint(
        name="imp_kvah",
        address=14742,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAh", description="輸入累積視在電量"),
    ),
    ReadPoint(
        name="exp_kvah",
        address=14744,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAh", description="輸出累積視在電量"),
    ),
    ReadPoint(
        name="tot_kvah",
        address=14736,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAh", description="總視在電量"),
    ),
    ReadPoint(
        name="ins_kw",
        address=14610,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="需量實功"),
    ),
    ReadPoint(
        name="ins_kvar",
        address=14612,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAR", description="需量虛功"),
    ),
    ReadPoint(
        name="ins_kva",
        address=14614,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVA", description="需量視在"),
    ),
    ReadPoint(
        name="acc_kw",
        address=14622,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="累積需量實功"),
    ),
    ReadPoint(
        name="acc_kvar",
        address=14624,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.LITTLE_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kVAR", description="累積需量虛功"),
    ),
]
