from csp_lib.modbus import ByteOrder, FunctionCode, UInt16, UInt32
from csp_lib.equipment.core import ReadPoint, pipeline, ScaleTransform, RoundTransform
from csp_lib.equipment.core.point import PointMetadata

# SE4900 Branch Power Meter - point definitions (no alarm definitions)
# Source: Referance.py SE4900 class (lines 809-825)

SE4900_pm_read_points = [
    ReadPoint(
        name="acc_kwh",
        address=0x0000,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(1), RoundTransform(0)),
        metadata=PointMetadata(unit="kWh", description="累積電量"),
    ),
    ReadPoint(
        name="v",
        address=0x0002,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="電壓"),
    ),
    ReadPoint(
        name="i",
        address=0x0004,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="A", description="電流"),
    ),
    ReadPoint(
        name="p",
        address=0x0006,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="實功功率"),
    ),
    ReadPoint(
        name="v_a",
        address=0x0008,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="A相電壓"),
    ),
    ReadPoint(
        name="v_b",
        address=0x000A,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="B相電壓"),
    ),
    ReadPoint(
        name="v_c",
        address=0x000C,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.1), RoundTransform(1)),
        metadata=PointMetadata(unit="V", description="C相電壓"),
    ),
    ReadPoint(
        name="i_a",
        address=0x000E,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="A", description="A相電流"),
    ),
    ReadPoint(
        name="i_b",
        address=0x0010,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="A", description="B相電流"),
    ),
    ReadPoint(
        name="i_c",
        address=0x0012,
        data_type=UInt32(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="A", description="C相電流"),
    ),
    ReadPoint(
        name="p_a",
        address=0x0020,
        data_type=UInt16(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="A相功率"),
    ),
    ReadPoint(
        name="p_b",
        address=0x0021,
        data_type=UInt16(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="B相功率"),
    ),
    ReadPoint(
        name="p_c",
        address=0x0022,
        data_type=UInt16(),
        function_code=FunctionCode.READ_HOLDING_REGISTERS,
        byte_order=ByteOrder.BIG_ENDIAN,
        pipeline=pipeline(ScaleTransform(0.001), RoundTransform(3)),
        metadata=PointMetadata(unit="kW", description="C相功率"),
    ),
]
